name: WakaTime Update

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update WakaTime stats
      uses: wakatime-action/update-readme@v1
      with:
        token: ${{ secrets.WAKATIME_API_KEY }}
        SHOW_OS: true
        SHOW_COMMIT: true
        SHOW_DAYS_OF_WEEK: true
        SHOW_EDITORS: true
        TIME_RANGE: all_time
        LANG_COUNT: 10
        SHOW_TIME: true
        SHOW_TOTAL: true
